### ISSUE TITLE
Hii bro , am working on an app using flutter local notification , am trying to add buttons to it but am getting errors when I click it , can U please help me to solve it ? 

### ISSUE THREAD

**Issue by ampro88** [iRawNewton/client-onboarding#1]

**Comment by iRawNewton** [comment]
Hi buddy. I would suggest you to please connect me through LinkedIn if you have one. It will be really easy to communicate.

Coming back to your question, I'm assuming you're using firebase messaging here. To add buttons on your notification, simply add following code under notification field

"actions": [
            {
                "title": "View",
                "action": "VIEW"
            },
            {
                "title": "Dismiss",
                "action": "DISMISS"
            }
        ]


I'm not an expert in this field yet so this code might produce an error. Feel free to reply.
